"""
HTML report renderer.

Generates a standalone HTML report with embedded CSS styling.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from spark_map.core.report import Report

from spark_map.core.findings import Severity


def render_html(report: Report) -> str:
    """Render a report as HTML."""
    findings_html = _render_findings(report)
    metrics_html = _render_metrics(report)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spark Map Report - {report.metrics.app_name or report.metrics.app_id}</title>
    <style>
        {CSS_STYLES}
    </style>
</head>
<body>
    <header>
        <h1>Spark Map Report</h1>
        <p class="subtitle">Generated {report.analysis_timestamp}</p>
    </header>

    <main>
        <section class="summary">
            <h2>Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <span class="label">Application</span>
                    <span class="value">{report.metrics.app_name or report.metrics.app_id}</span>
                </div>
                <div class="summary-card">
                    <span class="label">Duration</span>
                    <span class="value">{report.metrics.total_duration_ms / 1000:.1f}s</span>
                </div>
                <div class="summary-card">
                    <span class="label">Stages</span>
                    <span class="value">{report.metrics.num_stages} ({report.metrics.num_failed_stages} failed)</span>
                </div>
                <div class="summary-card">
                    <span class="label">Tasks</span>
                    <span class="value">{report.metrics.num_tasks} ({report.metrics.num_failed_tasks} failed)</span>
                </div>
                <div class="summary-card">
                    <span class="label">Executors</span>
                    <span class="value">{report.metrics.num_executors}</span>
                </div>
                <div class="summary-card">
                    <span class="label">Findings</span>
                    <span class="value">{len(report.findings)} total</span>
                </div>
            </div>
        </section>

        {_render_llm_summary(report)}

        <section class="findings">
            <h2>Findings</h2>
            {findings_html}
        </section>

        <section class="metrics">
            <h2>Stage Metrics</h2>
            {metrics_html}
        </section>
    </main>

    <footer>
        <p>Generated by <a href="https://github.com/yourusername/spark-map">Spark Map</a></p>
    </footer>
</body>
</html>"""


def _render_findings(report: Report) -> str:
    """Render findings section."""
    if not report.findings:
        return '<p class="no-findings">No performance issues detected.</p>'

    severity_classes = {
        Severity.CRITICAL: "critical",
        Severity.WARNING: "warning",
        Severity.INFO: "info",
    }

    findings_html = []
    for finding in report.findings.sorted_by_severity():
        severity_class = severity_classes.get(finding.severity, "info")
        stages = ", ".join(str(s) for s in finding.stage_ids) if finding.stage_ids else "N/A"

        llm_section = ""
        if finding.llm_explanation:
            llm_section = f'''
            <div class="llm-explanation">
                <strong>AI Explanation:</strong> {finding.llm_explanation}
            </div>'''

        findings_html.append(f'''
        <div class="finding {severity_class}">
            <div class="finding-header">
                <span class="severity-badge">{finding.severity.value.upper()}</span>
                <h3>{finding.title}</h3>
            </div>
            <div class="finding-body">
                <p><strong>Stages:</strong> {stages}</p>
                <p>{finding.description}</p>
                {llm_section}
                <div class="mitigation">
                    <strong>Suggestion:</strong> {finding.mitigation_hint}
                </div>
                <div class="tags">
                    {" ".join(f'<span class="tag">{tag}</span>' for tag in finding.mitigation_tags)}
                </div>
            </div>
        </div>''')

    return "\n".join(findings_html)


def _render_metrics(report: Report) -> str:
    """Render stage metrics table."""
    rows = []
    for stage in report.metrics.stages:
        rows.append(f'''
        <tr>
            <td>{stage.stage_id}</td>
            <td>{stage.stage_name[:40]}...</td>
            <td>{stage.num_tasks}</td>
            <td>{stage.duration_ms / 1000:.1f}s</td>
            <td>{stage.task_duration_median_ms}ms</td>
            <td>{stage.task_duration_max_ms}ms</td>
            <td>{_format_bytes(stage.shuffle_read_bytes)}</td>
            <td>{_format_bytes(stage.shuffle_write_bytes)}</td>
            <td>{_format_bytes(stage.disk_bytes_spilled)}</td>
        </tr>''')

    return f'''
    <table class="metrics-table">
        <thead>
            <tr>
                <th>Stage</th>
                <th>Name</th>
                <th>Tasks</th>
                <th>Duration</th>
                <th>Median Task</th>
                <th>Max Task</th>
                <th>Shuffle Read</th>
                <th>Shuffle Write</th>
                <th>Disk Spill</th>
            </tr>
        </thead>
        <tbody>
            {"".join(rows)}
        </tbody>
    </table>'''


def _render_llm_summary(report: Report) -> str:
    """Render LLM summary section if available."""
    if not report.llm_summary:
        return ""

    return f'''
    <section class="llm-summary">
        <h2>AI Summary</h2>
        <p class="provider">Generated by {report.llm_provider}</p>
        <div class="summary-content">
            {report.llm_summary}
        </div>
    </section>'''


def _format_bytes(num_bytes: int) -> str:
    """Format bytes as human-readable string."""
    if num_bytes == 0:
        return "0 B"
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if abs(num_bytes) < 1024.0:
            return f"{num_bytes:.1f} {unit}"
        num_bytes /= 1024.0
    return f"{num_bytes:.1f} PB"


CSS_STYLES = """
    :root {
        --critical: #dc3545;
        --warning: #ffc107;
        --info: #17a2b8;
        --bg: #f8f9fa;
        --card-bg: #ffffff;
        --text: #212529;
        --border: #dee2e6;
    }

    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        line-height: 1.6;
        color: var(--text);
        background: var(--bg);
        padding: 2rem;
    }

    header {
        margin-bottom: 2rem;
    }

    h1 {
        font-size: 2rem;
        margin-bottom: 0.5rem;
    }

    .subtitle {
        color: #6c757d;
    }

    h2 {
        font-size: 1.5rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid var(--border);
    }

    section {
        background: var(--card-bg);
        border-radius: 8px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    .summary-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 1rem;
    }

    .summary-card {
        background: var(--bg);
        padding: 1rem;
        border-radius: 4px;
        text-align: center;
    }

    .summary-card .label {
        display: block;
        font-size: 0.875rem;
        color: #6c757d;
    }

    .summary-card .value {
        display: block;
        font-size: 1.25rem;
        font-weight: 600;
    }

    .finding {
        border-left: 4px solid var(--info);
        padding: 1rem;
        margin-bottom: 1rem;
        background: var(--bg);
        border-radius: 0 4px 4px 0;
    }

    .finding.critical {
        border-left-color: var(--critical);
    }

    .finding.warning {
        border-left-color: var(--warning);
    }

    .finding-header {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        margin-bottom: 0.75rem;
    }

    .finding-header h3 {
        font-size: 1.1rem;
    }

    .severity-badge {
        font-size: 0.75rem;
        font-weight: 600;
        padding: 0.25rem 0.5rem;
        border-radius: 4px;
        color: white;
        background: var(--info);
    }

    .finding.critical .severity-badge {
        background: var(--critical);
    }

    .finding.warning .severity-badge {
        background: var(--warning);
        color: #212529;
    }

    .mitigation {
        margin-top: 0.75rem;
        padding: 0.75rem;
        background: #e8f5e9;
        border-radius: 4px;
    }

    .llm-explanation {
        margin-top: 0.75rem;
        padding: 0.75rem;
        background: #e3f2fd;
        border-radius: 4px;
    }

    .tags {
        margin-top: 0.75rem;
    }

    .tag {
        display: inline-block;
        font-size: 0.75rem;
        padding: 0.25rem 0.5rem;
        background: #e9ecef;
        border-radius: 4px;
        margin-right: 0.25rem;
    }

    .no-findings {
        color: #28a745;
        font-size: 1.1rem;
    }

    .metrics-table {
        width: 100%;
        border-collapse: collapse;
    }

    .metrics-table th,
    .metrics-table td {
        padding: 0.75rem;
        text-align: left;
        border-bottom: 1px solid var(--border);
    }

    .metrics-table th {
        background: var(--bg);
        font-weight: 600;
    }

    .metrics-table tr:hover {
        background: var(--bg);
    }

    .llm-summary .provider {
        font-size: 0.875rem;
        color: #6c757d;
        margin-bottom: 1rem;
    }

    .llm-summary .summary-content {
        background: #f0f4f8;
        padding: 1rem;
        border-radius: 4px;
        white-space: pre-wrap;
    }

    footer {
        text-align: center;
        padding: 2rem;
        color: #6c757d;
    }

    footer a {
        color: #007bff;
    }
"""
